
const Food=[
    {
        id:1,
        url:require("../component/Dashboard/image/snaks/s11.jpg"),
        rate:'176',
        title:'Veg Pakoda',
        quantity:'8 pieces',
        star:4.5,
        description:'Classic Indian Veg Pakoda.',
        titlename:'Snacks',
        titleId:1
    },
    {
        id:2,
        url:require("../component/Dashboard/image/snaks/s10.jpg"),
        rate:'220',
        title:'Panner Pakoda',
        quantity:'8 pieces',
        star:4.5,
        description:'Classic Indian Paneer Pakoda',
        fakerate:250,
        titlename:'Snacks',
        titleId:1
    },
    {
        id:3,
        url:require("../component/Dashboard/image/snaks/s9.jpg"),
        rate:'180',
        title:'Cheese Burst Potato with Garlic',
        quantity:'8 pieces',
        star:4.5,
        description:'Cheesy Potato with Garlic Topping',
        titlename:'Snacks',
        titleId:1
    },
    {
        id:4,
        url:require("../component/Dashboard/image/snaks/s8.jpg"),
        rate:'170',
        title:'Honey Chilly Potato',
        quantity:'1 Serve',
        star:3,
        description:"Chilly Potato with honey dressing.",
        titlename:'Snacks',
        titleId:1
    },
    {
        id:6,
        url:require("../component/Dashboard/image/snaks/s7.jpg"),
        rate:'185',
        title:'Veg 65 Dry',
        quantity:'1 Serve',
        star:4,
        description:'Veg Pakoda with chinese tossing.',
        titlename:'Snacks',
        titleId:1
    },
    {
        id:7,
        url:require("../component/Dashboard/image/snaks/s6.jpg"),
        rate:'190',
        title:'Veg Finger Szechwan',
        quantity:'1 Serve',
        star:5,
        description:'Veg Finger Szechwan',
        title:'Snacks',
        titleId:1,
        titlename:'Snacks',
        titleId:1
    },
    {
        id:8,
        url:require("../component/Dashboard/image/snaks/s5.jpg"),
        rate:'245',
        title:'Golden Fried Babycorn with Hot Garlic Sauce',
        quantity:'1 Serve',
        star:4.5,
        description:'Golden Fried Babycorn with Hot Garlic ',
        titlename:'Snacks',
        titleId:1
    },
    {
        id:9,
        url:require("../component/Dashboard/image/snaks/s4.jpg"),
        rate:'185',
        title:'Veg Manchurian',
        quantity:'8 pieces',
        star:5,
        description:'Veg Manchurian Gracy / Dry',
        titlename:'Snacks',
        titleId:1
    },
    {
        id:10,
        url:require("../component/Dashboard/image/snaks/s3.jpg"),
        rate:'185',
        title:'Veg Momos',
        quantity:'8 pieces',
        star:5,
        description:'Nepali Momos with Chutney.',
        titlename:'Snacks',
        titleId:1
    },
    {
        id:11,
        url:require("../component/Dashboard/image/snaks/s2.jpg"),
        rate:'100',
        title:'Parotta',
        quantity:'3 pieces',
        star:5,
        description:'Parotta or Porotta is a layered Indian and Sri Lankan flatbread made from Maida or Atta, alternatively known as flaky ribbon pancake.',
        titlename:'Snacks',
        titleId:1
    },
    {
        id:12,
        url:require("../component/Dashboard/image/snaks/s1.jpg"),
        rate:'140',
        title:'French Fry',
        quantity:'1 Serve',
        star:5,
        description:'Classic Fresh Fries with Ketchup',
        titlename:'Snacks',
        titleId:1
    },
    {
        id:13,
        url:require("../component/Dashboard/image/kebab/8.jpg"),
        rate:220,
        title:'Veg Seekh Kabab',
        quantity:'1 Serve',
        star:4.5,
        description:'Delicious vegetarian Seekh Kababs made with spices.',
        titlename:'KababFood',
        titleId:2
    },
    {
        id:14,
        url:require("../component/Dashboard/image/kebab/7.jpg"),
        rate:165,
        title:'Tandoori Aloo',
        quantity:'1 Serve',
        star:4,
        description:'Tandoori roasted potatoes with Indian spices.',
        titlename:'KababFood',
        titleId:2
    },
    {
        id:15,
        url:require("../component/Dashboard/image/kebab/6.jpg"),
        rate:195,
        title:'Tandoori Gobhi',
        quantity:'1 Serve',
        star:4.5,
        description:'Cauliflower marinated in spices and tandoor roasted.',
        titlename:'KababFood',
        titleId:2
    },
    {
        id:16,
        url:require("../component/Dashboard/image/kebab/5.jpg"),
        rate:270,
        title:'Makai Malai Seekh Kabab',
        quantity:'1 Serve',
        star:5,
        description:'Creamy corn-based Seekh Kabab, grilled to perfection.',
        titlename:'KababFood',
        titleId:2
    },
    {
        id:17,
        url:require("../component/Dashboard/image/kebab/4.jpg"),
        rate:260,
        title:'Paneer Tikka',
        quantity:'1 Serve',
        star:4.5,
        description:'Soft paneer cubes marinated in spices and grilled.',
        titlename:'KababFood',
        titleId:2
    },
    {
        id:18,
        url:require("../component/Dashboard/image/kebab/3.jpg"),
        rate:290,
        title:'Paneer Malai Kabab',
        quantity:'1 Serve',
        star:4.8,
        description:'Paneer cooked in a creamy marinade and grilled.',
        titlename:'KababFood',
        titleId:2
    },
    {
        id:19,
        url:require("../component/Dashboard/image/kebab/2.jpg"),
        rate:180,
        title:'Hara Bhara Kabab',
        quantity:'1 Serve',
        star:4.2,
        description:'Spinach and vegetable-based green Kababs.',
        titlename:'KababFood',
        titleId:2
    },
    {
        id:20,
        url:require("../component/Dashboard/image/kebab/1.jpg"),
        rate:20,
        title:'Moti Seekh Kabab',
        quantity:'1 Serve',
        star:4.5,
        description:'Mini kababs made with spiced vegetables.',
        titlename:'KababFood',
        titleId:2
    },
    {
        id:21,
        url:require("../component/Dashboard/image/kebab/6.jpg"),
        rate:265,
        title:'Tandoori Bay Corn',
        quantity:'1 Serve',
        star:4.6,
        description:'Baby corn marinated and roasted in 5.',
        titlename:'KababFood',
        titleId:2
    },
    {
        id:22,
        url:require("../component/Dashboard/image/kebab/4.jpg"),
        rate:265,
        title:'Achari Mushroom',
        quantity:'1 Serve',
        star:4.7,
        description:'Pickle-flavored mushrooms roasted in tandoor.',
        titlename:'KababFood',
        titleId:2
    },
    {
        id:23,
        url:require("../component/Dashboard/image/kebab/3.jpg"),
        rate:280,
        title:'Stuffed Tandoori Mushroom',
        quantity:'1 Serve',
        star:4.9,
        description:'Mushrooms stuffed with a delicious mixture and roasted.',
        titlename:'KababFood',
        titleId:2
    },
    {
        id:24,
        url:require("../component/Dashboard/image/kebab/2.jpg"),
        rate:305,
        title:"Chef's Special Veg Kabab",
        quantity:'1 Serve',
        star:5,
        description:"Chef's unique recipe for special veg kababs.",
        titlename:'KababFood',
        titleId:2
    },
    {
        id:25,
        url:require("../component/Dashboard/image/kebab/1.jpg"),
        rate:610,
        title:'Veg Tandoori Platter',
        quantity:'12 pieces',
        star:5,
        description:'A platter of 12 assorted veg tandoori kababs.',
        titlename:'KababFood',
        titleId:2
    },
    {
        id:26,
        url:require("../component/Dashboard/image/kebab/6.jpg"),
        rate:280,
        title:'Chicken Tikka',
        quantity:'1 Serve',
        star:4.7,
        description:'Juicy chicken marinated and grilled in tandoor.',
        titlename:'KababFood',
        titleId:2
    },
    {
        id:27,
        url:require("../component/Dashboard/image/kebab/5.jpg"),
        rate:290,
        title:'Chicken Afghani Tikka',
        quantity:'1 Serve',
        star:4.8,
        description:'Rich and creamy chicken tikka cooked to perfection.',
        titlename:'KababFood',
        titleId:2
    },
    {
        id:28,
        url:require("../component/Dashboard/image/kebab/4.jpg"),
        rate:275,
        title:'Chicken Pahari Tikka',
        quantity:'1 Serve',
        star:4.6,
        description:'Pahari-style chicken tikka with mountain spices.',
        titlename:'KababFood',
        titleId:2
    },
    {
        id:29,
        url:require("../component/Dashboard/image/kebab/3.jpg"),
        rate:290,
        title:'Banjara Kebab',
        quantity:'1 Serve',
        star:4.5,
        description:'Chicken kebab marinated with rustic spices.',
        titlename:'KababFood',
        titleId:2
    },
    {
        id:30,
        url:require("../component/Dashboard/image/kebab/2.jpg"),
        rate:315,
        title:'Chicken Kalmi Kebab',
        quantity:'3 pieces',
        star:4.7,
        description:'Marinated chicken kebabs grilled to perfection.',
        titlename:'KababFood',
        titleId:2
    },
    {
        id:31,
        url:require("../component/Dashboard/image/kebab/1.jpg"),
        rate:315,
        title:'Chicken Tangari',
        quantity:'2 pieces',
        star:4.7,
        description:'Tandoori grilled chicken drumsticks.',
        titlename:'KababFood',
        titleId:2
    },
    {
        id:32,
        url:require("../component/Dashboard/image/kebab/8.jpg"),
        rate:315,
        title:'Leg Kebab',
        quantity:'2 pieces',
        star:4.7,
        description:'Succulent chicken leg pieces, marinated and grilled.',
        titlename:'KababFood',
        titleId:2
    },
    {
        id:33,
        url:require("../component/Dashboard/image/kebab/7.jpg"),
        rate:290,
        title:'Chicken Adraki Kabab',
        quantity:'1 Serve',
        star:4.5,
        description:'Chicken kebabs infused with ginger.',
        titlename:'KababFood',
        titleId:2
    },
    {
        id:34,
        url:require("../component/Dashboard/image/kebab/3.jpg"),
        rate:330,
        title:'Seekh Kabab',
        quantity:'1 Serve',
        star:5,
        description:'Classic Seekh kababs made with chicken mince and spices.',
        titlename:'KababFood',
        titleId:2
    },
    {
        id:35,
        url:require("../component/Dashboard/image/kebab/5.jpg"),
        rate:305,
        title:'Chicken Reshmi Kebab',
        quantity:'8 pieces',
        star:5,
        description:'Silky smooth chicken kebabs.',
        titlename:'KababFood',
        titleId:2
    },
    {
        id:36,
        url:require("../component/Dashboard/image/kebab/1.jpg"),
        rate:290,
        title:'Chicken Lahsooni',
        quantity:'1 Serve',
        star:4.8,
        description:'Chicken kababs with a garlicky flavor.',
        titlename:'KababFood',
        titleId:2
    },
    {
        id:37,
        url:require("../component/Dashboard/image/kebab/8.jpg"),
        rate:290,
        title:'Kalimirch Kebab',
        quantity:'1 Serve',
        star:4.8,
        description:'Chicken kababs with black pepper spices.',
        titlename:'KababFood',
        titleId:2
    },
    {
        id:38,
        url:require("../component/Dashboard/image/kebab/2.jpg"),
        rate:270,
        title:'Chicken Afghani Tandoor',
        quantity:'Half',
        star:4.5,
        description:'Creamy Afghani style tandoori chicken.',
        titlename:'KababFood',
        titleId:2
    },
    {
        id:39,
        url:require("../component/Dashboard/image/kebab/4.jpg"),
        rate:520,
        title:'Chicken Afghani Tandoor',
        quantity:'Full',
        star:5,
        description:'Creamy Afghani style tandoori chicken.',
        titlename:'KababFood',
        titleId:2
    },
    {
        id:40,
        url:require("../component/Dashboard/image/kebab/5.jpg"),
        rate:260,
        title:'Chicken Tandoori',
        quantity:'Half',
        star:4.5,
        description:'Traditional tandoori chicken, half portion.',
        titlename:'KababFood',
        titleId:2
    },
    {
        id:41,
        url:require("../component/Dashboard/image/kebab/3.jpg"),
        rate:500,
        title:'Chicken Tandoori',
        quantity:'Full',
        star:5,
        description:'Traditional tandoori chicken, full portion.',
        titlename:'KababFood',
        titleId:2
    },
    {
        id:42,
        url:require("../component/Dashboard/image/kebab/2.jpg"),
        rate:380,
        title:'Mutton Boti Kabab',
        quantity:'1 Serve',
        star:4.8,
        description:'Juicy mutton chunks grilled on skewers.',
        titlename:'KababFood',
        titleId:2
    },
    {
        id:43,
        url:require("../component/Dashboard/image/kebab/1.jpg"),
        rate:390,
        title:'Mutton Seekh Kabab',
        quantity:'1 Serve',
        star:5,
        description:'Minced mutton Seekh kababs with spices.',
        titlename:'KababFood',
        titleId:2
    },
    {
        id:44,
        url:require("../component/Dashboard/image/kebab/7.jpg"),
        rate:340,
        title:'Fish Tandoori',
        quantity:'1 Serve',
        star:4.7,
        description:'Tandoori cooked spiced fish fillets.',
        titlename:'KababFood',
        titleId:2
    },
    {
        id:45,
        url:require("../component/Dashboard/image/kebab/2.jpg"),
        rate:425,
        title:'Jhinga Tandoori',
        quantity:'1 Serve',
        star:5,
        description:'Tandoori cooked jumbo prawns.',
        titlename:'KababFood',
        titleId:2
    },
    {
        id:46,
        url:require("../component/Dashboard/image/kebab/1.jpg"),
        rate:370,
        title:'Fish Tikka',
        quantity:'1 Serve',
        star:4.5,
        description:'Boneless fish tikka pieces marinated and grilled.',
        titlename:'KababFood',
        titleId:2
    },
    {
        id:1,
        url:require("../component/Dashboard/image/soups/su8.jpg"),
        rate:90,
        title:'Clear Soup',
        quantity:'1 Serve',
        star:4,
        description:'Light and healthy clear vegetable soup.',
        titlename:'Soups',
        titleId:3
    },
    {
        id:2,
        url:require("../component/Dashboard/image/soups/su7.jpg"),
        rate:110,
        title:'Chicken Clear Soup',
        quantity:'1 Serve',
        star:4.5,
        description:'Clear soup with tender chicken pieces.',
        titlename:'Soups',
        titleId:3
    },
    {
        id:3,
        url:require("../component/Dashboard/image/soups/su6.jpg"),
        rate:105,
        title:'Sweet Corn Soup',
        quantity:'1 Serve',
        star:4.2,
        description:'Sweet and creamy corn soup.',
        titlename:'Soups',
        titleId:3
    },
    {
        id:4,
        url:require("../component/Dashboard/image/soups/su5.jpg"),
        rate:115,
        title:'Chicken Sweet Corn Soup',
        quantity:'1 Serve',
        star:4.5,
        description:'Sweet corn soup with shredded chicken.',
        titlename:'Soups',
        titleId:3
    },
    {
        id:5,
        url:require("../component/Dashboard/image/soups/su4.jpg"),
        rate:105,
        title:'Cream of Tomato Soup',
        quantity:'1 Serve',
        star:4.3,
        description:'Rich and creamy tomato soup.',
        titlename:'Soups',
        titleId:3
    },
    {
        id:6,
        url:require("../component/Dashboard/image/soups/su3.jpg"),
        rate:115,
        title:'Cream of Chicken Soup',
        quantity:'1 Serve',
        star:4.5,
        description:'Creamy soup with tender chicken pieces.',
        titlename:'Soups',
        titleId:3
    },
    {
        id:7,
        url:require("../component/Dashboard/image/soups/su2.jpg"),
        rate:105,
        title:'Manchow Soup',
        quantity:'1 Serve',
        star:4.2,
        description:'Spicy soup garnished with fried noodles.',
        titlename:'Soups',
        titleId:3
    },
    {
        id:8,
        url:require("../component/Dashboard/image/soups/su1.jpg"),
        rate:115,
        title:'Chicken Manchow Soup',
        quantity:'1 Serve',
        star:4.6,
        description:'Spicy Manchow soup with chicken.',
        titlename:'Soups',
        titleId:3
    },
    {
        id:9,
        url:require("../component/Dashboard/image/soups/su8.jpg"),
        rate:105,
        title:'Hot and Sour Soup',
        quantity:'1 Serve',
        star:4.3,
        description:'Tangy and spicy hot and sour soup.',
        titlename:'Soups',
        titleId:3
    },
    {
        id:10,
        url:require("../component/Dashboard/image/soups/su7.jpg"),
        rate:120,
        title:'Chicken Hot and Sour Soup',
        quantity:'1 Serve',
        star:4.5,
        description:'Hot and sour soup with chicken pieces.',
        titlename:'Soups',
        titleId:3
    },
    {
        id:11,
        url:require("../component/Dashboard/image/soups/su6.jpg"),
        rate:105,
        title:'Tum-Yum Soup',
        quantity:'1 Serve',
        star:4.4,
        description:'Thai-inspired tangy Tum-Yum soup.',
        titlename:'Soups',
        titleId:3
    },
    {
        id:12,
        url:require("../component/Dashboard/image/soups/su5.jpg"),
        rate:115,
        title:'Chicken Tum-Yum Soup',
        quantity:'1 Serve',
        star:4.6,
        description:'Thai Tum-Yum soup with chicken.',
        titlename:'Soups',
        titleId:3
    },
    {
        id:13,
        url:require("../component/Dashboard/image/soups/su4.jpg"),
        rate:105,
        title:'Lemon Coriander Soup',
        quantity:'1 Serve',
        star:4.2,
        description:'Light and tangy lemon coriander soup.',
        titlename:'Soups',
        titleId:3
    },
    {
        id:14,
        url:require("../component/Dashboard/image/soups/su3.jpg"),
        rate:135,
        title:'Chicken Lemon Coriander Soup',
        quantity:'1 Serve',
        star:4.6,
        description:'Lemon coriander soup with chicken.',
        titlename:'Soups',
        titleId:3
    },
    {
        id:15,
        url:require("../component/Dashboard/image/soups/su2.jpg"),
        rate:130,
        title:'Chicken Lung-Fung Soup',
        quantity:'1 Serve',
        star:4.7,
        description:'Flavorful chicken Lung-Fung soup.',
        titlename:'Soups',
        titleId:3
    },
    {
        id:16,
        url:require("../component/Dashboard/image/soups/su1.jpg"),
        rate:130,
        title:'Egg Drop Chicken Soup',
        quantity:'1 Serve',
        star:4.5,
        description:'Chicken soup with a silky egg drop finish.',
        titlename:'Soups',
        titleId:3
    },
    {
        id:17,
        url:require("../component/Dashboard/image/soups/su5.jpg"),
        rate:125,
        title:"Chef's Special Soup",
        quantity:'1 Serve',
        star:5,
        description:'The chef’s secret special recipe soup.',
        titlename:'Soups',
        titleId:3
    },
    {
        id:18,
        url:require("../component/Dashboard/image/soups/su3.jpg"),
        rate:150,
        title:"Chef's Special Chicken Soup",
        quantity:'1 Serve',
        star:5,
        description:'The chef’s special chicken soup.',
        titlename:'Soups',
        titleId:3
    },
    {  
        id: 37,  
        url: require("../component/Dashboard/image/mainCourse/m1.jpg"),  
        rate: 225,  
        title: "Dum Aloo Kashmiri",  
        quantity: "1 Serve",  
        star: 4.5,  
        description: "Delicious Kashmiri-style Dum Aloo.",  
        titlename: "MainCourse",  
        titleId: 4  
    },  
    {  
        id: 38,  
        url: require("../component/Dashboard/image/mainCourse/m2.jpg"),  
        rate: 195,  
        title: "Dum Aloo Panjabi",  
        quantity: "1 Serve",  
        star: 4,  
        description: "Punjabi-style Dum Aloo.",  
        titlename: "MainCourse",  
        titleId: 4  
    },  
    {  
        id: 39,  
        url: require("../component/Dashboard/image/mainCourse/m3.jpg"),  
        rate: 215,  
        title: "Veg Kadhai",  
        quantity: "1 Serve",  
        star: 4,  
        description: "Spicy and flavorful Veg Kadhai.",  
        titlename: "MainCourse",  
        titleId: 4  
    },  
    {  
        id: 40,  
        url: require("../component/Dashboard/image/mainCourse/m4.jpg"),  
        rate: 215,  
        title: "Veg Handi",  
        quantity: "1 Serve",  
        star: 4.5,  
        description: "Rich and creamy Veg Handi.",  
        titlename: "MainCourse",  
        titleId: 4  
    },  
    {  
        id: 41,  
        url: require("../component/Dashboard/image/mainCourse/m5.jpg"),  
        rate: 230,  
        title: "Veg Deewani Handi",  
        quantity: "1 Serve",  
        star: 5,  
        description: "Delicious Veg Deewani Handi.",  
        titlename: "MainCourse",  
        titleId: 4  
    },  
    {  
        id: 42,  
        url: require("../component/Dashboard/image/mainCourse/m6.jpg"),  
        rate: 230,  
        title: "Veg Patiyala",  
        quantity: "1 Serve",  
        star: 4.5,  
        description: "Flavorsome Veg Patiyala.",  
        titlename: "MainCourse",  
        titleId: 4  
    },  
    {  
        id: 43,  
        url: require("../component/Dashboard/image/mainCourse/m7.jpg"),  
        rate: 175,  
        title: "Seasonal Veg Parwal",  
        quantity: "1 Serve",  
        star: 4,  
        description: "Seasonal special Parwal dish.",  
        titlename: "MainCourse",  
        titleId: 4  
    },  
    {  
        id: 44,  
        url: require("../component/Dashboard/image/mainCourse/m8.jpg"),  
        rate: 175,  
        title: "Seasonal Veg Bhindi",  
        quantity: "1 Serve",  
        star: 4,  
        description: "Seasonal special Bhindi dish.",  
        titlename: "MainCourse",  
        titleId: 4  
    },  
    {  
        id: 45,  
        url: require("../component/Dashboard/image/mainCourse/m1.jpg"),  
        rate: 175,  
        title: "Seasonal Veg Brinjal",  
        quantity: "1 Serve",  
        star: 4,  
        description: "Seasonal special Brinjal dish.",  
        titlename: "MainCourse",  
        titleId: 4  
    },  
    {  
        id: 46,  
        url: require("../component/Dashboard/image/mainCourse/m2.jpg"),  
        rate: 295,  
        title: "Paneer Lajawab",  
        quantity: "1 Serve",  
        star: 5,  
        description: "Lajawab Paneer in creamy gravy.",  
        titlename: "MainCourse",  
        titleId: 4  
    },
    {  
        id: 47,  
        url: require("../component/Dashboard/image/mainCourse/m3.jpg"),  
        rate: 320,  
        title: "Kaju Curry",  
        quantity: "1 Serve",  
        star: 4.5,  
        description: "Delicious Kaju curry with rich flavors.",  
        titlename: "MainCourse",  
        titleId: 4  
    },  
    {  
        id: 48,  
        url: require("../component/Dashboard/image/mainCourse/m4.jpg"),  
        rate: 270,  
        title: "Paneer Jhalfrezi",  
        quantity: "1 Serve",  
        star: 4,  
        description: "Spicy Paneer Jhalfrezi with seasonal vegetables.",  
        titlename: "MainCourse",  
        titleId: 4  
    },  
    {  
        id: 49,  
        url: require("../component/Dashboard/image/mainCourse/m5.jpg"),  
        rate: 270,  
        title: "Paneer Kadhai",  
        quantity: "1 Serve",  
        star: 4.5,  
        description: "Paneer cooked in a flavorful Kadhai-style gravy.",  
        titlename: "MainCourse",  
        titleId: 4  
    },  
    {  
        id: 50,  
        url: require("../component/Dashboard/image/mainCourse/m6.jpg"),  
        rate: 270,  
        title: "Paneer Handi",  
        quantity: "1 Serve",  
        star: 4.5,  
        description: "Paneer cooked in a rich, creamy handi-style gravy.",  
        titlename: "MainCourse",  
        titleId: 4  
    },  
    {  
        id: 51,  
        url: require("../component/Dashboard/image/mainCourse/m7.jpg"),  
        rate: 270,  
        title: "Paneer do Pyaza",  
        quantity: "1 Serve",  
        star: 4,  
        description: "Paneer cooked with onions in a spicy gravy.",  
        titlename: "MainCourse",  
        titleId: 4  
    },  
    {  
        id: 52,  
        url: require("../component/Dashboard/image/mainCourse/m8.jpg"),  
        rate: 290,  
        title: "Paneer Tikka Masala (6pcs)",  
        quantity: "1 Serve",  
        star: 4.5,  
        description: "Paneer Tikka served with rich masala gravy.",  
        titlename: "MainCourse",  
        titleId: 4  
    },  
    {  
        id: 53,  
        url: require("../component/Dashboard/image/mainCourse/m1.jpg"),  
        rate: 270,  
        title: "Paneer Butter Masala",  
        quantity: "1 Serve",  
        star: 5,  
        description: "Paneer cooked in a rich butter gravy.",  
        titlename: "MainCourse",  
        titleId: 4  
    },  
    {  
        id: 54,  
        url: require("../component/Dashboard/image/mainCourse/m2.jpg"),  
        rate: 265,  
        title: "Mushroom do Pyaza",  
        quantity: "1 Serve",  
        star: 4,  
        description: "Mushrooms cooked in a spicy onion-based gravy.",  
        titlename: "MainCourse",  
        titleId: 4  
    },  
    {  
        id: 55,  
        url: require("../component/Dashboard/image/mainCourse/m3.jpg"),  
        rate: 265,  
        title: "Mushroom Masaledar",  
        quantity: "1 Serve",  
        star: 4,  
        description: "Mushrooms cooked in a masaledar gravy.",  
        titlename: "MainCourse",  
        titleId: 4  
    },  
    {  
        id: 56,  
        url: require("../component/Dashboard/image/mainCourse/m4.jpg"),  
        rate: 270,  
        title: "Mushroom Baby Corn Kadhai",  
        quantity: "1 Serve",  
        star: 4.5,  
        description: "Mushrooms and Baby Corn cooked in Kadhai-style spices.",  
        titlename: "MainCourse",  
        titleId: 4  
    },  
    {  
        id: 57,  
        url: require("../component/Dashboard/image/mainCourse/m5.jpg"),  
        rate: 150,  
        title: "Egg Masala",  
        quantity: "1 Serve",  
        star: 4,  
        description: "Eggs cooked in spicy masala gravy.",  
        titlename: "MainCourse",  
        titleId: 4  
    },
    {  
        id: 58,  
        url: require("../component/Dashboard/image/mainCourse/m6.jpg"),  
        rate: 325,  
        title: "Chicken Patiyala (Boneless)",  
        quantity: "1 Serve",  
        star: 4.5,  
        description: "Boneless chicken cooked in a flavorful Patiyala-style gravy.",  
        titlename: "MainCourse",  
        titleId: 4  
    },  
    {  
        id: 59,  
        url: require("../component/Dashboard/image/mainCourse/m8.jpg"),  
        rate: 280,  
        title: "Murgh Saag Wala",  
        quantity: "1 Serve",  
        star: 4.5,  
        description: "Chicken cooked with saag (spinach) in a mild gravy.",  
        titlename: "MainCourse",  
        titleId: 4  
    },  
    {  
        id: 60,  
        url: require("../component/Dashboard/image/mainCourse/m1.jpg"),  
        rate: 310,  
        title: "Murgh Rara",  
        quantity: "1 Serve",  
        star: 4.5,  
        description: "A delicious and spicy chicken dish with unique flavors.",  
        titlename: "MainCourse",  
        titleId: 4  
    },  
    {  
        id: 61,  
        url: require("../component/Dashboard/image/mainCourse/m2.jpg"),  
        rate: 295,  
        title: "Chicken Tikka Masala (6pcs)",  
        quantity: "1 Serve",  
        star: 5,  
        description: "Juicy chicken tikka pieces cooked in a rich, creamy masala gravy.",  
        titlename: "MainCourse",  
        titleId: 4  
    },  
    {  
        id: 62,  
        url: require("../component/Dashboard/image/mainCourse/m3.jpg"),  
        rate: 310,  
        title: "Chicken Tikka Reshmi Kabab Masala (6pcs)",  
        quantity: "1 Serve",  
        star: 4.5,  
        description: "A blend of soft, flavorful Reshmi Kababs cooked in a delicious masala gravy.",  
        titlename: "MainCourse",  
        titleId: 4  
    },  
    {  
        id: 63,  
        url: require("../component/Dashboard/image/mainCourse/m4.jpg"),  
        rate: 270,  
        title: "Chicken Tariwali (4pcs)",  
        quantity: "1 Serve",  
        star: 4,  
        description: "Chicken pieces cooked in tangy, spicy gravy.",  
        titlename: "MainCourse",  
        titleId: 4  
    },  
    {  
        id: 64,  
        url: require("../component/Dashboard/image/mainCourse/m5.jpg"),  
        rate: 280,  
        title: "Murgh Dehati (Half)",  
        quantity: "1 Serve",  
        star: 4.5,  
        description: "Traditional Dehati-style chicken with a flavorful rustic gravy.",  
        titlename: "MainCourse",  
        titleId: 4  
    },  
    {  
        id: 65,  
        url: require("../component/Dashboard/image/mainCourse/m7.jpg"),  
        rate: 550,  
        title: "Murgh Dehati (Full)",  
        quantity: "1 Serve",  
        star: 4.5,  
        description: "Full serving of Murgh Dehati with rich gravy.",  
        titlename: "MainCourse",  
        titleId: 4  
    },  
    {  
        id: 66,  
        url: require("../component/Dashboard/image/mainCourse/m8.jpg"),  
        rate: 295,  
        title: "Haveli Ki Taang (Half)",  
        quantity: "1 Serve",  
        star: 4.5,  
        description: "Delicious lamb leg cooked in a rich, aromatic gravy (Half).",  
        titlename: "MainCourse",  
        titleId: 4  
    },  
    {  
        id: 67,  
        url: require("../component/Dashboard/image/mainCourse/m1.jpg"),  
        rate: 590,  
        title: "Haveli Ki Taang (Full)",  
        quantity: "1 Serve",  
        star: 5,  
        description: "Full serving of lamb leg cooked in aromatic gravy.",  
        titlename: "MainCourse",  
        titleId: 4  
    },  
    {  
        id: 68,  
        url: require("../component/Dashboard/image/mainCourse/m2.jpg"),  
        rate: 325,  
        title: "Murgh Hyderabadi Keema Masala",  
        quantity: "1 Serve",  
        star: 5,  
        description: "Hyderabadi-style keema chicken cooked with spices.",  
        titlename: "MainCourse",  
        titleId: 4  
    },
    {  
        id: 69,  
        url: require("../component/Dashboard/image/rice/r9.jpg"),  
        rate: 105,  
        title: "Plain Rice",  
        quantity: "1 Serve",  
        star: 4,  
        description: "Simple steamed rice, served as a base for any curry or gravy.",  
        titlename: "Rice",  
        titleId: 5  
    },  
    {  
        id: 70,  
        url: require("../component/Dashboard/image/rice/r8.jpg"),  
        rate: 120,  
        title: "Jeera Rice",  
        quantity: "1 Serve",  
        star: 4.5,  
        description: "Steamed rice flavored with cumin seeds and light spices.",  
        titlename: "Rice",  
        titleId: 5  
    },  
    {  
        id: 71,  
        url: require("../component/Dashboard/image/rice/r7.jpg"),  
        rate: 175,  
        title: "Veg Fried Rice",  
        quantity: "1 Serve",  
        star: 4.5,  
        description: "Fried rice with a medley of vegetables and aromatic spices.",  
        titlename: "Rice",  
        titleId: 5  
    },  
    {  
        id: 72,  
        url: require("../component/Dashboard/image/rice/r6.jpg"),  
        rate: 165,  
        title: "Egg Fried Rice",  
        quantity: "1 Serve",  
        star: 4,  
        description: "Fried rice with scrambled eggs and a hint of seasoning.",  
        titlename: "Rice",  
        titleId: 5  
    },  
    {  
        id: 73,  
        url: require("../component/Dashboard/image/rice/r5.jpg"),  
        rate: 195,  
        title: "Chicken Fried Rice",  
        quantity: "1 Serve",  
        star: 4.5,  
        description: "Fried rice with tender chicken pieces, cooked with spices.",  
        titlename: "Rice",  
        titleId: 5  
    },  
    {  
        id: 74,  
        url: require("../component/Dashboard/image/rice/r4.jpg"),  
        rate: 195,  
        title: "Veg Schezwan Fried Rice",  
        quantity: "1 Serve",  
        star: 4.5,  
        description: "Spicy Schezwan fried rice with mixed vegetables and aromatic spices.",  
        titlename: "Rice",  
        titleId: 5  
    },  
    {  
        id: 75,  
        url: require("../component/Dashboard/image/rice/r3.jpg"),  
        rate: 210,  
        title: "Chicken Schezwan Fried Rice",  
        quantity: "1 Serve",  
        star: 5,  
        description: "Schezwan-style fried rice with chicken pieces and bold spices.",  
        titlename: "Rice",  
        titleId: 5  
    },  
    {  
        id: 76,  
        url: require("../component/Dashboard/image/rice/r2.jpg"),  
        rate: 210,  
        title: "Veg Triple Schezwan Fried Rice",  
        quantity: "1 Serve",  
        star: 4.5,  
        description: "A fiery blend of Schezwan fried rice with triple vegetables.",  
        titlename: "Rice",  
        titleId: 5  
    },  
    {  
        id: 77,  
        url: require("../component/Dashboard/image/rice/r1.jpg"),  
        rate: 230,  
        title: "Chicken Triple Schezwan Fried Rice",  
        quantity: "1 Serve",  
        star: 5,  
        description: "Schezwan fried rice with triple servings of chicken and spices.",  
        titlename: "Rice",  
        titleId: 5  
    },
    {  
        id: 78,  
        url: require("../component/Dashboard/image/roti/1.jpg"),  
        rate: 25,  
        title: "Tawa Roti",  
        quantity: "1 Piece",  
        star: 4,  
        description: "Soft and warm traditional tawa roti.",  
        titlename: "Roti",  
        titleId: 6  
    },  
    {  
        id: 79,  
        url: require("../component/Dashboard/image/roti/2.jpg"),  
        rate: 30,  
        title: "Butter Tawa Roti",  
        quantity: "1 Piece",  
        star: 4.5,  
        description: "Classic tawa roti brushed with a generous amount of butter.",  
        titlename: "Roti",  
        titleId: 6  
    },  
    {  
        id: 80,  
        url: require("../component/Dashboard/image/roti/3.jpg"),  
        rate: 25,  
        title: "Roti Paln",  
        quantity: "1 Piece",  
        star: 4,  
        description: "Traditional roti served with a flavorful paln mix.",  
        titlename: "Roti",  
        titleId: 6  
    },  
    {  
        id: 81,  
        url: require("../component/Dashboard/image/roti/4.jpg"),  
        rate: 30,  
        title: "Roti Butter",  
        quantity: "1 Piece",  
        star: 4.5,  
        description: "Soft roti served with a dollop of butter.",  
        titlename: "Roti",  
        titleId: 6  
    },  
    {  
        id: 82,  
        url: require("../component/Dashboard/image/roti/5.jpg"),  
        rate: 40,  
        title: "Missi Roti",  
        quantity: "1 Piece",  
        star: 4.5,  
        description: "Spiced chickpea flour roti, a flavorful alternative to regular roti.",  
        titlename: "Roti",  
        titleId: 6  
    },  
    {  
        id: 83,  
        url: require("../component/Dashboard/image/roti/6.jpg"),  
        rate: 40,  
        title: "Makki Roti",  
        quantity: "1 Piece",  
        star: 4,  
        description: "Cornmeal roti, a traditional accompaniment to various Punjabi dishes.",  
        titlename: "Roti",  
        titleId: 6  
    },  
    {  
        id: 84,  
        url: require("../component/Dashboard/image/roti/7.jpg"),  
        rate: 310,  
        title: "Roti Ki Todki (6pcs)",  
        quantity: "6 Pieces",  
        star: 5,  
        description: "Crispy fried roti pieces served with a tangy dip.",  
        titlename: "Roti",  
        titleId: 6  
    }
        
        ]
            
                
export default Food